# Generated by Django 2.1.3 on 2018-12-15 20:19

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Login', max_length=200)),
                ('account_year', models.PositiveSmallIntegerField(default=2018, help_text='Format: <YYYY>', validators=[django.core.validators.MinValueValidator(2017), django.core.validators.MaxValueValidator(2050)])),
                ('account_month', models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('account_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('account_booked', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.SmallIntegerField(default=1)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2018, 12, 15, 21, 19, 38, 809578))),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_info', models.CharField(help_text='Buchungs Info', max_length=200)),
                ('booking_booked', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'ordering': ['account_id', '-pos'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='account_pos',
            unique_together={('account_id', 'pos')},
        ),
    ]
