# Generated by Django 2.1.3 on 2018-12-15 22:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20181215_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_base',
            name='account_start_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='account_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 23, 41, 42, 631814)),
        ),
    ]
