# Generated by Django 2.1.3 on 2018-12-17 21:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20181215_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_month',
            field=models.PositiveSmallIntegerField(default=0, help_text='Format: <MM>', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_year',
            field=models.PositiveSmallIntegerField(default=2018, help_text='Format: <YYYY>', validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='account_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 22, 42, 48, 763294)),
        ),
    ]
