# Generated by Django 2.1.3 on 2018-12-17 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20181217_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_pos',
            name='booking_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 17, 22, 43, 20, 160544)),
        ),
    ]
